// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.URLUnshortener
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("source")]
        public Uri Source { get; set; }

        [JsonProperty("destination")]
        public Uri Destination { get; set; }

        [JsonProperty("unshortened")]
        public bool Unshortened { get; set; }

        [JsonProperty("reason")]
        public object Reason { get; set; }
    }
}
